# https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run
# Make sure to enable Cloud Run Admin role for the service account
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/robohash:latest', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/robohash:latest']
 # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'robohash'
    - '--image'
    - 'gcr.io/$PROJECT_ID/robohash:latest'
    - '--region'
    - 'us-central1'
images:
  - 'gcr.io/$PROJECT_ID/robohash:latest'
